#!/bin/bash

#
# Compute idle jobs for every user
# At first we find all the users with condor_status -submitters -total command and grep just the usernames
# After that summarize IdleJobs (second column) for every user with awk
#

AWK="/bin/awk"
CONDOR_STATUS="/usr/bin/condor_status"
USERS=$(${CONDOR_STATUS} -submitters -total | grep -oP '\.\w*@' | grep -oP '[a-z]+[0-9]*' | sort | uniq)

for i in ${USERS}; do echo -n "User: $i, "; ${CONDOR_STATUS} -submitters -total | grep -w $i | ${AWK} '{ sum += $3 } END { print "waiting jobs: " sum }'; done
