#!/bin/bash

#
# Finds how many jobs have been completed on target server in the timedelta period
# Uses condor_history command with -name and -constraint options
# First mandatory argument of this script is the name of the server, second and third argument is the datetime
# We compute the number of completed jobs with wc utility
#
# Usage:
# ./6-jobs-hour-range condor.farm.particle.cz "12/04/2017 01:00:00" "12/06/2017 09:50:12"
#

CONDOR_HISTORY="/usr/bin/condor_history"
DATETIME_SINCE=$(date -d "$2" +%s)
DATETIME_UNTIL=$(date -d "$3" +%s)

if [ -z "$1" ]
then
  echo -e ""
  echo -e "Error: please set server name, start date and end date as a arguments to this command.\n"
  echo -e 'Usage:  ./6-jobs-hour-range condor.farm.particle.cz "12/04/2017 01:00:00" "12/06/2017 09:50:12"\n'
  echo -e "You can use these servers: \n"
  find_server_names
else
  FINISHED_JOBS=$(${CONDOR_HISTORY} -name "$1" -constraint "CompletionDate >= "${DATETIME_SINCE}" && CompletionDate <= ${DATETIME_UNTIL} && JobStatus == 4" | grep -cw C)
  echo -e "Completed jobs on ${1} from ${2}, to ${3}: ${FINISHED_JOBS}"
fi
