#!/bin/bash

#
# Finds how many users are in every user group
# 

AWK="/bin/awk"
CONDOR_USERPRIO="/usr/bin/condor_userprio"
EGREP="/bin/egrep"

${CONDOR_USERPRIO} -hierarchical | ${EGREP} -v '^[A-Z]|^\s+[A-Z]|--' | ${AWK} 'BEGIN { count=0 }; /group_/ {if (count); print "Number of users in group", $1, count; count=0; next} {count++}'
