#!/bin/bash

#
# Running and waiting jobs for user group
#
# Usage:
# ./9-jobs-groups
#

AWK="/bin/awk"
CONDOR_STATUS="/usr/bin/condor_status"
GROUP_NAMES=$(condor_userprio -allusers | grep -oP '\w+_\w+' | uniq | cut -d "_" -f 2)

for i in ${GROUP_NAMES}; do echo -e "Group $i: " $(${CONDOR_STATUS} -submitters -total | ${AWK} -v pattern="$i" 'BEGIN { sum1=0; sum2=0 }; $0 ~ pattern { sum1 += $2; sum2 += $3 } END { print "Running jobs: "sum1; print ", waiting jobs: "sum2 }'); done
