#!/bin/bash

export LC_ALL=C

CONDOR_STATUS="/usr/bin/condor_status"
USERS=$(${CONDOR_STATUS} -submitters -total | grep -oP '\.\w*@' | grep -oP '[a-z]+[0-9]*' | sort | uniq)

for i in ${USERS}; do 
    echo -e ""; 
    IS_EMPTY=$(${CONDOR_STATUS} -af GLobalJobId RemoteOwner | grep -w ${i} | cut -d "#" -f 1 | sort | uniq | wc -l); 
    if [ "${IS_EMPTY}" -eq "0" ]; then
	echo -e "${i} - no running jobs for this user at the moment"
    else 
	echo -e "${i}'s jobs are running on: "; 
	${CONDOR_STATUS} -af GLobalJobId RemoteOwner | grep -w ${i} | cut -d "#" -f 1 | sort | uniq; 
    fi
done
