#!/bin/bash

#
# Finds how many jobs have been completed on target server for every user in the past hours
# Uses condor_history command with -name and -constraint options
# First mandatory argument of this script is the name of the server, second argument is the number of hours
# We compute the number of completed jobs with grep's -c option
#

AWK="/bin/awk"
CONDOR_HISTORY="/usr/bin/condor_history"
CONDOR_FUNCTIONS="/home/strachon/scripts/find-server-names"
CONDOR_STATUS="/usr/bin/condor_status"
NOW_TIMESTAMP=$(date +%s)
USERS=$(${CONDOR_STATUS} -submitters -total | grep -oP '\.\w*@' | grep -oP '[a-z]+[0-9]*' | sort | uniq)

source ${CONDOR_FUNCTIONS}

if [ -z "$1" ]
then
  echo -e ""
  echo -e "Please set server name and number of hours passed as a argument to this command.\n"
  echo -e "Usage: ./16-servers-jobs-user-hour condor.farm.particle.cz 5\n"
  echo -e "You can use these servers: \n"
  find_server_names
else
  HOURS_BACK="$(($2 * 60))"
  HOURS_TIMESTAMP="$(($NOW_TIMESTAMP - $HOURS_BACK))"
  for i in ${USERS}; do echo -e "Completed jobs on ${1} for user ${i} in past ${2} hours: " $(${CONDOR_HISTORY} -name "$1" -constraint "CompletionDate >= ${HOURS_TIMESTAMP} && JobStatus == 4" | grep -c ${i}); done
fi
