#!/bin/bash

#
# Finds how many jobs have been completed on target server in the past hours
# Uses condor_history command with -name and -constraint options
# First mandatory argument of this script is the name of the server, second argument is the number of hours
# We compute the number of completed jobs with wc utility
#
# Usage:
# ./5-completed-jobs-hours condor.farm.particle.cz 5
#

CONDOR_FUNCTIONS="/home/strachon/scripts/htcondor.inc"

source ${CONDOR_FUNCTIONS}

check-args $1

function main() {
  HOURS_BACK="$(($2 * 3600))"
  NOW_TIMESTAMP=$(date +%s)
  HOURS_TIMESTAMP="$(($NOW_TIMESTAMP - $HOURS_BACK))"
  FINISHED_JOBS=$(${CONDOR_HISTORY} -name "$1" -constraint "CompletionDate >= ${HOURS_TIMESTAMP} && JobStatus == 4" | grep -cw C)
  echo -e "Completed jobs on ${1} in past ${2} hours: ${FINISHED_JOBS}"
}

main $1 $2
